version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    container_name: deneme1-postgres
    environment:
      POSTGRES_DB: deneme1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - deneme1-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: deneme1-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - deneme1-network

  # API
  api:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    container_name: deneme1-api
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/deneme1
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-jwt-secret
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend/api:/app
      - /app/node_modules
    networks:
      - deneme1-network

  # Web
  web:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    container_name: deneme1-web
    environment:
      REACT_APP_API_URL: http://localhost:3001/api
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./frontend/web:/app
      - /app/node_modules
    networks:
      - deneme1-network

volumes:
  postgres_data:
  redis_data:

networks:
  deneme1-network:
    driver: bridge
