apiVersion: v1
kind: ServiceMonitor
metadata:
  name: enterprise-flutter-monitor
  namespace: enterprise-flutter
  labels:
    app: enterprise-flutter-app
spec:
  selector:
    matchLabels:
      app: enterprise-flutter-app
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: v1
kind: Service
metadata:
  name: enterprise-flutter-metrics
  namespace: enterprise-flutter
  labels:
    app: enterprise-flutter-app
spec:
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
  selector:
    app: enterprise-flutter-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: enterprise-flutter
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      - "alert_rules.yml"
    
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093
    
    scrape_configs:
      - job_name: 'enterprise-flutter'
        static_configs:
          - targets: ['enterprise-flutter-metrics:9090']
        metrics_path: /metrics
        scrape_interval: 30s
        scrape_timeout: 10s
