openapi: 3.0.3
info:
  title: Sales API
  description: API for sales management system
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://staging-api.example.com/v1
    description: Staging server

paths:
  /sales:
    get:
      summary: Get all sales
      description: Retrieve a list of all sales
      tags:
        - Sales
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Sale'
                  meta:
                    $ref: '#/components/schemas/Meta'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Sale:
      type: object
      required:
        - id
        - title
        - total
      properties:
        id:
          type: string
          description: Unique identifier for the sale
          example: "S-001"
        title:
          type: string
          description: Title of the sale
          example: "Örnek Satış"
        total:
          type: number
          format: double
          description: Total amount of the sale
          example: 499.90
        createdAt:
          type: string
          format: date-time
          description: When the sale was created
        updatedAt:
          type: string
          format: date-time
          description: When the sale was last updated

    Meta:
      type: object
      properties:
        total:
          type: integer
          description: Total number of items
        page:
          type: integer
          description: Current page number
        limit:
          type: integer
          description: Number of items per page

    Error:
      type: object
      required:
        - message
        - code
      properties:
        message:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
        details:
          type: object
          description: Additional error details
