name: Deploy POS System

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.4'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Run tests
      run: flutter test
    
    - name: Run code generation
      run: flutter packages pub run build_runner build --delete-conflicting-outputs

  build-windows:
    needs: test
    runs-on: windows-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.4'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build Windows
      run: flutter build windows --dart-define=FLUTTER_ENV=production
    
    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: build/windows/x64/runner/Release/

  build-android:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.4'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build Android
      run: flutter build apk --dart-define=FLUTTER_ENV=production
    
    - name: Upload Android Artifact
      uses: actions/upload-artifact@v3
      with:
        name: android-build
        path: build/app/outputs/flutter-apk/

  build-web:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.4'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build Web
      run: flutter build web --dart-define=FLUTTER_ENV=production
    
    - name: Upload Web Artifact
      uses: actions/upload-artifact@v3
      with:
        name: web-build
        path: build/web/
