name: Release

on:
  push:
    tags:
      - 'v*'

env:
  FLUTTER_VERSION: '3.35.4'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build all platforms
        run: |
          flutter build web --release
          flutter build windows --release
          flutter build apk --release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/web/**
            build/windows/**
            build/app/outputs/flutter-apk/**
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
