apiVersion: apps/v1
kind: Deployment
metadata:
  name: deneme1-api-staging
  namespace: deneme1-staging
  labels:
    app: deneme1-api
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deneme1-api
      environment: staging
  template:
    metadata:
      labels:
        app: deneme1-api
        environment: staging
    spec:
      containers:
      - name: api
        image: deneme1/api:staging
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: deneme1-staging-config
              key: NODE_ENV
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: deneme1-staging-config
              key: DATABASE_URL
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: deneme1-staging-config
              key: REDIS_HOST
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: deneme1-staging-secrets
              key: JWT_SECRET
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
